name: Multiplatform Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write # for vcpkg binary cache

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ./.github/actions/project-constants
      id: constants

    - name: Setup
      run: >
        cmake -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" 
        -B build -S . 

    - name: Build      
      run: > 
        cmake --build build 
        --config Release
        --target ${{ steps.constants.outputs.project-name }}_TEST

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config Release