name: Multiplatform Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write # for vcpkg binary cache

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ./.github/actions/project-constants
      id: constants
    - uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        manifest-dir: ${{ github.workspace }}
        triplet: x64-windows-release
        token: ${{ github.token }}
        github-binarycache: true

    - name: Setup
      run: cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B build -S . 

    - name: Build      
      run: > 
        cmake --build build 
        --config Release
        --target ${{ steps.constants.outputs.project-name }}_TEST

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config Release